on:
  push:
  schedule:
    - cron: "38 22 * * *" # 早上6点45左右推送

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2

      - name: python env
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.23

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine
          pip install bs4

      - name: 'Get DataSource'
        run: curl https://news.topurl.cn > ./result.html

      - name: 'Get Info'
        run: python ./getInfo.py

      - name: 'Get Date'
        run: |
          echo "REPORT_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
          echo "TODAY_DATE=$(TZ=':Asia/Shanghai' date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 'Get TEXT'
        run: |
            echo 'FILE_TEXT<<EOF' >> $GITHUB_ENV
            cat ./result.txt >> $GITHUB_ENV
            echo 'EOF' >> $GITHUB_ENV

      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.163.com
          server_port: 465
          username: ${{ secrets.MAIL_USER_NMAE }}
          password: ${{ secrets.MAIL_PWD }}
          subject: 今日新闻简报推送 (${{env.REPORT_DATE}})
          body: file://result.txt
          to: coutureone@163.com
          from: GitHub Actions
          content_type: text/html

      - name: '发送到钉钉群 (使用curl)'
        env:
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}   # 基础URL，不包含签名参数
          DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}     # 加签密钥
        run: |
          # 安装必要的工具（如果系统没有的话）
          sudo apt-get update -y
          sudo apt-get install -y openssl coreutils
          
          # 获取当前时间戳（毫秒）
          timestamp=$(date +%s%3N)
          
          # 计算签名
          string_to_sign="${timestamp}\n${DINGTALK_SECRET}"
          sign=$(echo -ne "$string_to_sign" | openssl dgst -sha256 -hmac "$DINGTALK_SECRET" -binary | base64 | tr -d '\n')
          
          # URL编码签名
          sign=$(echo $sign | sed 's/+/%2B/g; s/\//%2F/g; s/=/%3D/g')
          
          # 构造完整URL
          url="${DINGTALK_WEBHOOK}&timestamp=${timestamp}&sign=${sign}"
          
          # 构建JSON消息体
          # 注意：需要转义双引号和特殊字符
          content=$(echo "${{env.FILE_TEXT}}" | sed 's/"/\\"/g' | sed "s/'/\\\\'/g")
          
          # 创建JSON数据
          json_data="{
            \"msgtype\": \"text\",
            \"text\": {
              \"content\": \"$content\"
            },
            \"at\": {
              \"isAtAll\": true
            }
          }"
          
          # 发送请求
          echo "发送钉钉消息..."
          curl -v -s "$url" \
               -H "Content-Type: application/json" \
               -d "$json_data"
          
          echo "钉钉消息发送完成！"

      # Telegram通知（可选）
      # - name: Telegram通知
      #   run: |
      #     curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
      #     -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
      #     -d "text=${{env.FILE_TEXT}}"

      - name: '打完收工,提交代码!'
        run: |
          git config --local user.email "couturecome@gamil.com"
          git config --local user.name "coutureone"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.MYGG_TOKEN }}@github.com/${{ github.repository }}
          git pull
          currentDate=${{env.TODAY_DATE}}
          mkdir -p  ${currentDate%%-*} && cp result.txt ${currentDate%%-*}/${currentDate}.txt
          git add .
          git commit -m "Update By Github Action Bot"
          git push